### ISSUE TITLE
multiple writers gets an error

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/cloudmesh-pi-burn#15]
```
(ENV3) pi@red:~/cloudmesh_pi_burn $ cm-pi-burn detect

# ----------------------------------------------------------------------
# Detecting USB Card Reader
# ----------------------------------------------------------------------

Make sure the USB Reader is removed ...
Is the reader removed? (Y/n) Y
Now plug in the Reader ...
Is the reader plugged in? (Y/n) y

# ----------------------------------------------------------------------
# Detected Card Writer
# ----------------------------------------------------------------------

Bus 002 Device 008: ID 05e3:0749 Genesys Logic, Inc. 
Bus 002 Device 009: ID 05e3:0749 Genesys Logic, Inc. 
Bus 002 Device 004: ID 05e3:0749 Genesys Logic, Inc. 
Bus 002 Device 005: ID 05e3:0749 Genesys Logic, Inc. 
Bus 002 Device 007: ID 05e3:0749 Genesys Logic, Inc. 
Bus 002 Device 006: ID 05e3:0749 Genesys Logic, Inc. 

(ENV3) pi@red:~/cloudmesh_pi_burn $ cm-pi-burn info
cm-pi-burn: /home/pi/ENV3/bin/cm-pi-burn
dryrun:     False

# ----------------------------------------------------------------------
# Operating System
# ----------------------------------------------------------------------

Disk /dev/mmcblk0: 29.7 GiB, 31914983424 bytes, 62333952 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xea7d04d6

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk0p1        8192   532479   524288  256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      532480 62333951 61801472 29.5G 83 Linux
Traceback (most recent call last):
  File "/home/pi/ENV3/bin/cm-pi-burn", line 11, in <module>
    load_entry_point('cmburn', 'console_scripts', 'cm-pi-burn')()
  File "/home/pi/cloudmesh_pi_burn/cmburn/pi/cmpiburn.py", line 318, in main
    analyse(arguments)
  File "/home/pi/cloudmesh_pi_burn/cmburn/pi/cmpiburn.py", line 138, in analyse
    burner.info()
  File "/home/pi/cloudmesh_pi_burn/cmburn/pi/burner.py", line 157, in info
    'size': information.split("blocks:", 1)[1].split("\n", 1)[
IndexError: list index out of range
```

**Comment by laszewsk** [comment]
```
sudo fdisk -l
Disk /dev/ram0: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram1: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram2: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram3: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram4: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram5: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram6: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram7: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram8: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram9: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram10: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram11: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram12: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram13: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram14: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/ram15: 4 MiB, 4194304 bytes, 8192 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes


Disk /dev/mmcblk0: 29.7 GiB, 31914983424 bytes, 62333952 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xea7d04d6

Device         Boot  Start      End  Sectors  Size Id Type
/dev/mmcblk0p1        8192   532479   524288  256M  c W95 FAT32 (LBA)
/dev/mmcblk0p2      532480 62333951 61801472 29.5G 83 Linux


Disk /dev/sdb: 29.7 GiB, 31914983424 bytes, 62333952 sectors
Disk model: STORAGE DEVICE  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: C00CD0CA-194C-4D4E-AA59-EC7DC57E382E

Device      Start      End  Sectors  Size Type
/dev/sdb1      40   409639   409600  200M EFI System
/dev/sdb2  411648 62332927 61921280 29.5G Microsoft basic data


Disk /dev/sdd: 29.7 GiB, 31914983424 bytes, 62333952 sectors
Disk model: STORAGE DEVICE  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 27788EA5-258A-495F-A457-794C5AC4B7E7

Device      Start      End  Sectors  Size Type
/dev/sdd1      40   409639   409600  200M EFI System
/dev/sdd2  411648 62332927 61921280 29.5G Microsoft basic data


Disk /dev/sdf: 29.7 GiB, 31914983424 bytes, 62333952 sectors
Disk model: STORAGE DEVICE  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: C9BE1420-937B-4CFC-96CD-56E168C47D63

Device      Start      End  Sectors  Size Type
/dev/sdf1      40   409639   409600  200M EFI System
/dev/sdf2  411648 62332927 61921280 29.5G Microsoft basic data


Disk /dev/sdh: 29.7 GiB, 31914983424 bytes, 62333952 sectors
Disk model: STORAGE DEVICE  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: C4CFEEDF-D8CE-4AE5-BF83-8FBBF8038B21

Device      Start      End  Sectors  Size Type
/dev/sdh1      40   409639   409600  200M EFI System
/dev/sdh2  411648 62332927 61921280 29.5G Microsoft basic data


Disk /dev/sdj: 29.7 GiB, 31914983424 bytes, 62333952 sectors
Disk model: STORAGE DEVICE  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 67C27076-DC70-4840-9972-ACAE518BAC24

Device      Start      End  Sectors  Size Type
/dev/sdj1      40   409639   409600  200M EFI System
/dev/sdj2  411648 62332927 61921280 29.5G Microsoft basic data


Disk /dev/sdl: 29.7 GiB, 31914983424 bytes, 62333952 sectors
Disk model: STORAGE DEVICE  
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: 384B2D75-260F-4FA6-9E7B-BA922F61BDFC

Device      Start      End  Sectors  Size Type
/dev/sdl1      40   409639   409600  200M EFI System
/dev/sdl2  411648 62332927 61921280 29.5G Microsoft basic data
(ENV3) pi@red:~/cloudmesh_pi_burn $ cm-pi-burn info  
cm-pi-burn: /home/pi/ENV3/bin/cm-pi-burn
dryrun:     False


```
