### ISSUE TITLE
subprocess error on cmd.exe and powershell

### ISSUE THREAD

**Issue by jpfleischer** [cloudmesh/cloudmesh-pi-burn#65]
there is an issue with burn on windows branch.
```python
Shell.execute("rm", arguments=[
    '-f', filename])
```
line 1143 in cloudmesh-pi-burn/cloudmesh/burn/command/burn.py
this line breaks on powershell and cmd.exe but not gitbash

```bash
ERROR: problem executing subprocess

Trace:
Traceback (most recent call last):
      File "C:\Users\Sledgehammer\cm\cloudmesh-common\cloudmesh\common\Shell.py", line 406, in execute
        result = subprocess.check_output(
      File "C:\Users\Sledgehammer\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 420, in check_output
        return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
      File "C:\Users\Sledgehammer\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
        with Popen(*popenargs, **kwargs) as process:
      File "C:\Users\Sledgehammer\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 966, in __init__
        self._execute_child(args, executable, preexec_fn, close_fds,
      File "C:\Users\Sledgehammer\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1435, in _execute_child
        hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
    FileNotFoundError: [WinError 2] The system cannot find the file specified
```

**Comment by jpfleischer** [comment]
this has been solved thanks to Shell.rm
https://github.com/cloudmesh/cloudmesh-pi-burn/commit/aba4e52d04eb140b109dbe04ba21f589b86a8844

**Comment by jpfleischer** [comment]
we have forfeited the possibility of running burn on powershell and cmd.exe and we are only focusing on git bash right now
